# 实验唯一标识串
_key_:
  name: a
  model/optimizer/lr: lr
  model/model: model
  model/drop: drop
  model/dim: dim
  model/decay: wd
  DataLoader/batch_size: bs
  dataset/filter_rating: dfr
  dataset/source: ds

_grid_search_:
#  "model/optimizer/lr": [ 0.001, 0.003, 0.01, 0.03, 0.1, 0.3, 1.0 ]  # learning_rate
#  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4 ]
#  "model/decay": [ 0, 0.0001, 0.0003, 0.001, 0.003 ]
  "model/optimizer/lr": [ 0.1, 0.3, 1.0, 3.0, 10.0 ]  # learning_rate
  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6 ]
  "model/decay": [ 0.003, 0.01, 0.03, 0.1, 0.3 ]
  "DataLoader/batch_size": [1024, 2048, 4096, 8192, 16384, 26870]
#  "DataLoader/batch_size": '[1024*2**i for i in range(5)]'
_grid_search_repeat: 3
gpus: "[0, 1, 3, 2] * 5 + [0, 3] * 6"

cuda: "1"
name: BPR
model:
  dim: 32
  model: BPR
  drop: 0.2
  decay: 0.003
  optimizer:
    lr: 0.3

DataLoader:
  batch_size: 26870

dataset:
  source: AIV # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
