# 实验唯一标识串
_key_:
  name: a
  model/optimizer/lr: lr
  model/model: model
  model/drop: drop
  model/dim: dim
  model/decay: wd
  model/alpha: alpha
  DataLoader/batch_size: bs
  dataset/filter_rating: dfr
  dataset/source: ds

_grid_search_:
#  "model/optimizer/lr": [ 0.1, 0.3, 1.0, 3.0, 10.0 ]  # learning_rate
#  "model/drop": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6 ]
#  "model/decay": [ 0.003, 0.01, 0.03, 0.1, 0.3 ]
#  "model/alpha": [ 0.01, 0.03, 0.1, 0.3, 0.5, 0.7, 0.9, 0.97, 0.99 ]
  "model/alpha": [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 ]
#  "DataLoader/batch_size": [1024, 2048, 4096, 8192, 16384, 26870]
_grid_search_repeat: 1
gpus: "[0, 1, 3, 2] * 5 + [0, 3] * 6"

cuda: "1"
name: UmBPRModel
model:
  dim: 32
  model: UmBPRModel
  drop: 0.2
  alpha: 0.0
  decay: 0.03
  optimizer:
    lr: 1.0

DataLoader:
  batch_size: 26870

dataset:
  source: AIV # ML1MDataset # CiteULikeDataset / ML100KDataset
  filter_rating: 0
  split_mode: leave-one-out
  fast: True
